<?php

/**
 * ScmFaturaDoc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class ScmFaturaDoc extends BaseScmFaturaDoc
{
	public function preInsert ($event) {
		$this->id_usuario = Zend_Auth::getInstance()->getIdentity()->id;
		$this->dt_sistema = DMG_Date::now();
	}
	public function postUpdate ($event) {
		if ($this->id_fatura_doc_status == 2) {
			foreach ($this->ScmFaturaItem as $k) {
				$now = new Zend_Date();
				$d1 = new Zend_Date(($k->ScmMaquina->dt_ultima_transformacao == null) ? 0 : $k->ScmMaquina->dt_ultima_transformacao);
				$d2 = new Zend_Date(($k->ScmMaquina->dt_ultima_regularizacao == null) ? 0 : $k->ScmMaquina->dt_ultima_regularizacao);
				$d3 = new Zend_Date(($k->ScmMaquina->dt_ultima_movimentacao == null) ? 0 : $k->ScmMaquina->dt_ultima_movimentacao);
				$d4 = new Zend_Date(($k->ScmMaquina->dt_ultimo_faturamento == null) ? 0 : $k->ScmMaquina->dt_ultimo_faturamento);
				$d5 = new Zend_Date(($k->ScmMaquina->dt_ultimo_status == null) ? 0 : $k->ScmMaquina->dt_ultimo_status);
				$dt = new Zend_Date(($k->ScmFaturaDoc->dt_fatura == null) ? 0 : $k->ScmFaturaDoc->dt_fatura);

				if ($dt->compare($d1) == 1 && $dt->compare($d2) == 1 && $dt->compare($d3) == 1 && $dt->compare($d4) == 1 && $dt->compare($d5) == 1) {
					$k->ScmMaquina->nr_cont_1 = $k->nr_cont_1;
					$k->ScmMaquina->nr_cont_2 = $k->nr_cont_2;
					$k->ScmMaquina->nr_cont_3 = $k->nr_cont_3;
					$k->ScmMaquina->nr_cont_4 = $k->nr_cont_4;
					$k->ScmMaquina->nr_cont_5 = $k->nr_cont_5;
					$k->ScmMaquina->nr_cont_6 = $k->nr_cont_6;
				}
				$k->ScmMaquina->dt_ultimo_faturamento = $k->ScmFaturaDoc->dt_fatura;
		      	$k->ScmMaquina->save();
			}
		}
	}
}